using static Bricklayer.Core.Common.World.BlockType;

namespace Bricklayer.Core.Common.World
{
    /// <summary>
    /// Represents an instance of a tile in the world.
    /// </summary>
    /// <remarks>
    /// This is a struct for memory effeciency.
    /// </remarks>
    public struct Tile
    {
        public const int BackgroundIndex = 0, ForegroundIndex = 1;
        public const int Width = 16, Height = 16, DrawHeight = 20, DrawWidth = 20;

        /// <summary>
        /// The layer (foreground or background) the tile occupies.
        /// </summary>
        public Layer Layer => Type.Layer;

        /// <summary>
        /// The type of block this tile is.
        /// </summary>
        public BlockType Type
        {
            get { return FromID(type); }
            set { type = value.ID; }
        }

        /// <summary>
        /// The type of the tile, in ID form. A list of types is generated by the server on startup.
        /// (As IDs vary depending on the plugins loaded)
        /// </summary>
        private short type;

        public Tile(BlockType type)
        {
            this.type = type.ID;
        }
    }
}